use_frameworks!

platform :ios, '8.0'

target 'XUNCrashShield_Example' do
  pod 'XUNCrashShield', :path => '../'

  target 'XUNCrashShield_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
